configs:
  rbac:
    policy.default: role:readonly
    policy.csv: |-
      p, role:frodo-admin, applications, *, */*, allow
      p, role:frodo-admin, applicationsets, *, */*, allow
      p, role:frodo-admin, clusters, *, *, allow
      p, role:frodo-admin, repositories, *, *, allow
      p, role:frodo-admin, projects, *, *, allow
      g, frodoAdmin, role:frodo-admin
  cm:
    accounts.frodoAdmin: apiKey
    users.anonymous.enabled: true
  params:
    server.insecure: true